name: Daily Email Sender

on:
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 10:00 PM IST (16:00 UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies (if required)
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Run Email Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python send_email.py
