name: Daily Email Sender

on:
  schedule:
    - cron: '0 16 * * *' # Runs every day at 10:00 PM IST (16:00 UTC)
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y sendemail libio-socket-ssl-perl libnet-ssleay-perl

      - name: Send Email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }} # Store this in GitHub Secrets
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }} # Store this in GitHub Secrets
        run: |
          sendemail -f "admission@rjcollege.edu.in" \
                    -xu "$EMAIL_USER" \
                    -xp "$EMAIL_PASS" \
                    -s "smtp-relay.brevo.com:587" \
                    -t "samaniwahiduddin382@gmail.com" \
                    -t "user2@example.com" \
                    -t "user3@example.com" \
                    -t "user4@example.com" \
                    -t "user5@example.com" \
                    -u "Attendance Reminder" \
                    -m "Dear Student,

We have noticed irregular attendance in your classes. Regular attendance is vital for your academic progress and overall success.

If you are facing any challenges, feel free to reach out for support. Please ensure regular attendance moving forward." \
                    -o tls=yes \
                    -o message-header="From: R.J. College <admission@rjcollege.edu.in>"
